[build]
  command = "apt-get update && apt-get install -y build-essential && bundle install && bundle exec rake assets:precompile"
  publish = "public"

[build.environment]
  BUNDLE_WITHOUT = "development:test"